"use client";
import { useState } from "react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { navigation, roleLabels } from "@/lib/navigation";
import type { CurrentUser, UserRole } from "@/lib/types";
import { Icon } from "./icons";
import { BrandLogo } from "./brand-logo";

export function AppShell({ user, children, onRoleChange }: { user: CurrentUser; children: React.ReactNode; onRoleChange: (role: UserRole) => void }) { const [collapsed, setCollapsed] = useState(false); const [mobileOpen, setMobileOpen] = useState(false); const pathname = usePathname(); const links = navigation.filter((item) => item.roles.includes(user.role)); const nav = <nav aria-label="Primary navigation"><p className="nav-label">Workspace</p>{links.map((item) => <Link onClick={() => setMobileOpen(false)} className={`nav-link ${pathname === item.href ? "nav-link-active" : ""}`} href={item.href} key={item.href}><Icon name={item.icon}/><span>{item.label}</span></Link>)}</nav>; return <div className="app-shell"><aside className={`sidebar ${collapsed ? "sidebar-collapsed" : ""} ${mobileOpen ? "sidebar-mobile-open" : ""}`}><BrandLogo className="brand" />{nav}<div className="sidebar-footer"><div className="preview-note"><span className="preview-dot"/>Preview mode</div><label className="role-select-label" htmlFor="role-switcher">View as</label><select id="role-switcher" value={user.role} onChange={(event) => onRoleChange(event.target.value as UserRole)}>{Object.entries(roleLabels).map(([role, label]) => <option key={role} value={role}>{label}</option>)}</select></div><button className="collapse-button" aria-label={collapsed ? "Expand navigation" : "Collapse navigation"} onClick={() => setCollapsed(!collapsed)}><Icon name="chevron"/><span>{collapsed ? "" : "Collapse sidebar"}</span></button></aside>{mobileOpen && <button className="mobile-scrim" aria-label="Close navigation" onClick={() => setMobileOpen(false)}/>}<div className="shell-main"><header className="topbar"><button className="mobile-menu" aria-label="Open navigation" onClick={() => setMobileOpen(true)}><Icon name="menu"/></button><div className="breadcrumb">Workspace <span>/</span> <strong>Dashboard</strong></div><div className="topbar-actions"><button className="icon-button" aria-label="Notifications"><Icon name="bell"/></button><div className="user-menu"><span className="avatar">{user.displayName.split(" ").map((name) => name[0]).join("")}</span><span className="user-name">{user.displayName}</span><Icon name="chevron" size={14}/></div></div></header><main>{children}</main></div></div>; }
