import type { ButtonHTMLAttributes, ReactNode } from "react";
import { titleCase } from "@/lib/format";
import type { CommissionStatus, CaseStatus, PaymentStatus, PayoutSettlementStatus, RegistrationFeeStatus, RegistrationStatus } from "@/lib/types";

export function Button({ variant = "primary", size = "md", children, className = "", ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { variant?: "primary" | "secondary" | "ghost" | "danger"; size?: "sm" | "md" }) { return <button className={`button button-${variant} button-${size} ${className}`} {...props}>{children}</button>; }
export function Badge({ status }: { status: CaseStatus | PaymentStatus | PayoutSettlementStatus | "partially_settled" | CommissionStatus | RegistrationStatus | RegistrationFeeStatus | "active" | "inactive" }) { const label = titleCase(status); const tone = ["active", "verified", "paid", "completed", "waived", "settled"].includes(status) ? "success" : ["pending", "partially_settled", "pending_payment", "pending_verification", "scheduled", "under_review", "draft", "pending_approval", "adjusted"].includes(status) ? "warning" : ["cancelled", "reversed", "withheld", "inactive", "rejected", "suspended", "refunded"].includes(status) ? "danger" : "neutral"; return <span className={`badge badge-${tone}`}><span className="badge-dot" aria-hidden="true" />{label}</span>; }
export function StatCard({ label, value, detail, accent = false }: { label: string; value: string; detail?: string; accent?: boolean }) { return <section className={`stat-card ${accent ? "stat-card-accent" : ""}`}><p className="eyebrow">{label}</p><p className="stat-value">{value}</p>{detail && <p className="stat-detail">{detail}</p>}</section>; }
export function EmptyState({ title = "Nothing here yet", description = "When records become available, they will appear here.", action }: { title?: string; description?: string; action?: ReactNode }) { return <div className="state-card"><div className="state-icon">⌁</div><h3>{title}</h3><p>{description}</p>{action}</div>; }
export function LoadingState() { return <div className="state-card" aria-label="Loading"><div className="skeleton skeleton-icon"/><div className="skeleton skeleton-line skeleton-title"/><div className="skeleton skeleton-line"/><div className="skeleton skeleton-line short"/></div>; }
export function ErrorState({ onRetry }: { onRetry?: () => void }) { return <div className="state-card"><div className="state-icon state-icon-danger">!</div><h3>We couldn’t load this view</h3><p>Check your connection and try again. Your data has not been changed.</p>{onRetry && <Button variant="secondary" onClick={onRetry}>Try again</Button>}</div>; }
export function PermissionDenied({ action }: { action?: ReactNode } = {}) { return <div className="state-card"><div className="state-icon state-icon-warning">↗</div><h3>You don’t have access to this area</h3><p>Your current role does not permit viewing this information. Contact an administrator if you need access.</p>{action}</div>; }
export function ConfirmationDialog({ open, title, description, confirmLabel = "Confirm", confirmVariant = "danger", onConfirm, onCancel }: { open: boolean; title: string; description: string; confirmLabel?: string; confirmVariant?: "primary" | "danger"; onConfirm: () => void; onCancel: () => void }) { if (!open) return null; return <div className="dialog-backdrop" role="presentation"><div className="dialog" role="dialog" aria-modal="true" aria-labelledby="dialog-title"><h2 id="dialog-title">{title}</h2><p>{description}</p><div className="dialog-actions"><Button variant="secondary" onClick={onCancel}>Cancel</Button><Button variant={confirmVariant} onClick={onConfirm}>{confirmLabel}</Button></div></div></div>; }
