import type { ButtonHTMLAttributes, ReactNode } from "react";
import { titleCase } from "@/lib/format";
import { Icon } from "./icons";
import { TextArea } from "./form-controls";
import { PopupModal } from "./popup-modal";
import type { PopupModalSize } from "./popup-modal";
import type { AccountStatus, CommissionStatus, CaseStatus, PaymentStatus, PayoutSettlementStatus, RegistrationFeeStatus, RegistrationStatus } from "@/lib/types";

export function Button({ variant = "primary", size = "md", children, className = "", ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { variant?: "primary" | "secondary" | "ghost" | "danger"; size?: "sm" | "md" }) { return <button className={`button button-${variant} button-${size} ${className}`} {...props}>{children}</button>; }
export function Badge({ status }: { status: CaseStatus | PaymentStatus | PayoutSettlementStatus | "partially_settled" | CommissionStatus | RegistrationStatus | RegistrationFeeStatus | AccountStatus }) { const label = titleCase(status); const tone = ["active", "active_installments", "verified", "paid", "completed", "waived", "settled"].includes(status) ? "success" : ["pending", "partially_settled", "pending_payment", "pending_verification", "scheduled", "under_review", "changes_requested", "draft", "pending_approval", "adjusted", "invited", "quotation_issued", "awaiting_deposit", "installation_pending_confirmation", "installation_scheduled", "installed_monitoring", "trial_review"].includes(status) ? "warning" : ["cancelled", "reversed", "withheld", "inactive", "rejected", "suspended", "refunded"].includes(status) ? "danger" : "neutral"; return <span className={`badge badge-${tone}`}><span className="badge-dot" aria-hidden="true" />{label}</span>; }
export function StatCard({ label, value, detail, accent = false }: { label: string; value: string; detail?: string; accent?: boolean }) { return <section className={`stat-card ${accent ? "stat-card-accent" : ""}`}><p className="eyebrow">{titleCase(label)}</p><p className="stat-value">{value}</p>{detail && <p className="stat-detail">{detail}</p>}</section>; }
export function EmptyState({ title = "Nothing here yet", description = "When records become available, they will appear here.", action, icon }: { title?: string; description?: string; action?: ReactNode; icon?: ReactNode }) { return <div className="state-card"><div className="state-icon">{icon ?? <Icon name="question" size={20}/>}</div><h3>{title}</h3><p>{description}</p>{action}</div>; }
export function LoadingState() { return <div className="state-card" aria-label="Loading"><div className="skeleton skeleton-icon"/><div className="skeleton skeleton-line skeleton-title"/><div className="skeleton skeleton-line"/><div className="skeleton skeleton-line short"/></div>; }
export function ErrorState({ onRetry, response }: { onRetry?: () => void; response?: string }) { return <div className="state-card"><div className="state-icon state-icon-danger">!</div><h3>We couldn’t load this view</h3>{response && <pre className="error-state-response" role="alert">{response}</pre>}{onRetry && <Button className="error-state-retry" variant="secondary" onClick={onRetry}>Try again</Button>}</div>; }
export function PermissionDenied({ action }: { action?: ReactNode } = {}) { return <div className="state-card"><div className="state-icon state-icon-warning">↗</div><h3>You don’t have access to this area</h3><p>Your current role does not permit viewing this information. Contact an administrator if you need access.</p>{action}</div>; }
export function ConfirmationDialog({ open, title, description, icon, size = "md", confirmLabel = "Confirm", confirmVariant = "danger", onConfirm, onCancel, reason, onReasonChange, reasonRequired = false, reasonLabel = "Reason", children, confirmDisabled = false, loading = false, footer }: { open: boolean; title: string; description: string; icon?: ReactNode; size?: PopupModalSize; confirmLabel?: string; confirmVariant?: "primary" | "danger"; onConfirm: () => void; onCancel: () => void; reason?: string; onReasonChange?: (value: string) => void; reasonRequired?: boolean; reasonLabel?: string; children?: ReactNode; confirmDisabled?: boolean; loading?: boolean; footer?: ReactNode }) { return <PopupModal open={open} title={title} description={description} icon={icon} size={size} onClose={onCancel} tone={confirmVariant === "danger" ? "danger" : "brand"} footer={footer ?? <div className="dialog-actions"><Button variant="secondary" onClick={onCancel} disabled={loading}>Cancel</Button><Button variant={confirmVariant} onClick={onConfirm} disabled={confirmDisabled || loading || (reasonRequired && !reason?.trim())} aria-busy={loading}>{loading && <span className="button-spinner" aria-hidden="true" />}{confirmLabel}</Button></div>}>{children}{loading && <p className="dialog-loading" role="status" aria-live="polite">Processing your request…</p>}{onReasonChange && <label className="case-field"><span>{reasonLabel}{reasonRequired ? " *" : ""}</span><TextArea value={reason ?? ""} onChange={(event) => onReasonChange(event.target.value)} placeholder="Enter a clear reason" required={reasonRequired} /></label>}</PopupModal>; }
