// Licensed commercial, Islamic, digital, and retail development banks that
// can receive domestic payouts in Malaysia. Review against BNM's Financial
// Sector Participants Directory when the list is updated.
export const MALAYSIAN_BANKS = [
  "AEON Bank (M) Berhad",
  "Affin Bank Berhad",
  "Affin Islamic Bank Berhad",
  "Agrobank",
  "Alliance Bank Malaysia Berhad",
  "Alliance Islamic Bank Berhad",
  "Al Rajhi Banking & Investment Corporation (Malaysia) Berhad",
  "AmBank (M) Berhad",
  "AmBank Islamic Berhad",
  "Bangkok Bank Berhad",
  "Bank Islam Malaysia Berhad",
  "Bank Muamalat Malaysia Berhad",
  "Bank Rakyat",
  "Bank Simpanan Nasional",
  "Boost Bank Berhad",
  "CIMB Bank Berhad",
  "CIMB Islamic Bank Berhad",
  "Citibank Berhad",
  "GX Bank Berhad",
  "Hong Leong Bank Berhad",
  "Hong Leong Islamic Bank Berhad",
  "HSBC Bank Malaysia Berhad",
  "HSBC Amanah Malaysia Berhad",
  "Industrial and Commercial Bank of China (Malaysia) Berhad",
  "KAF Digital Bank Berhad",
  "Malayan Banking Berhad (Maybank)",
  "Maybank Islamic Berhad",
  "MBSB Bank Berhad",
  "OCBC Bank (Malaysia) Berhad",
  "OCBC Al-Amin Bank Berhad",
  "Public Bank Berhad",
  "Public Islamic Bank Berhad",
  "RHB Bank Berhad",
  "RHB Islamic Bank Berhad",
  "Ryt Bank (YTL Digital Bank Berhad)",
  "Standard Chartered Bank Malaysia Berhad",
  "Standard Chartered Saadiq Berhad",
  "UOB Malaysia",
] as const;
