import type { AgentLevel, AgentSummary, DashboardSnapshot, UserRole } from "./types";
export const mockCases = [
  { id: "case-001", caseNumber: "SMG-00124", customerDisplayName: "Kencana Packaging Sdn Bhd", agentId: "agent-001", agentName: "Aisha Rahman", status: "active_installments" as const, paymentStatus: "verified" as const, saleAmountSen: 2450000, submittedAt: "2026-07-08T02:30:00Z", updatedAt: "2026-08-04T07:00:00Z" },
  { id: "case-002", caseNumber: "SMG-00125", customerDisplayName: "Bintang Hardware", agentId: "agent-001", agentName: "Aisha Rahman", status: "under_review" as const, paymentStatus: "pending_verification" as const, saleAmountSen: 1180000, submittedAt: "2026-07-28T06:15:00Z", updatedAt: "2026-08-05T03:20:00Z" },
  { id: "case-003", caseNumber: "SMG-00126", customerDisplayName: "Lestari Food Industries", agentId: "agent-002", agentName: "Daniel Lim", status: "awaiting_deposit" as const, paymentStatus: "not_recorded" as const, saleAmountSen: 3275000, submittedAt: "2026-07-30T01:05:00Z", updatedAt: "2026-08-03T08:40:00Z" },
  { id: "case-004", caseNumber: "SMG-00127", customerDisplayName: "Mutiara Office Suites", agentId: "agent-003", agentName: "Nadia Yusuf", status: "submitted" as const, paymentStatus: "not_recorded" as const, saleAmountSen: null, submittedAt: "2026-08-05T09:00:00Z", updatedAt: "2026-08-05T09:00:00Z" },
];
export const mockCommissions = [
  { id: "com-001", caseId: "case-001", caseNumber: "SMG-00124", recipientId: "agent-001", recipientName: "Aisha Rahman", recipientKind: "level_1_agent" as const, entitlementSen: 134750, firstPaymentSen: 104832, deferredBalanceSen: 29918, paidToDateSen: 104832, nextPaymentDate: "2026-09-15", nextPaymentSen: 1760, status: "paid" as const },
  { id: "com-002", caseId: "case-001", caseNumber: "SMG-00124", recipientId: "agent-002", recipientName: "Daniel Lim", recipientKind: "level_2_agent" as const, entitlementSen: 73500, firstPaymentSen: 26208, deferredBalanceSen: 47292, paidToDateSen: 0, nextPaymentDate: "2026-09-15", nextPaymentSen: 2782, status: "scheduled" as const },
];
export const buildQualification = (level: AgentLevel, successfulCases: number, directAgents: number, annualSalesSen: number) => {
  const nextLevel: AgentLevel | null = level === 1 ? 2 : level === 2 ? 3 : null;
  const requiredCases = level === 1 ? 6 : null;
  const requiredDirectAgents = level === 1 ? 1 : level === 2 ? 30 : null;
  const requiredAnnualSalesSen = level === 2 ? 300000000 : null;
  const eligibleForPromotion = nextLevel !== null && (requiredCases === null || successfulCases >= requiredCases) && (requiredDirectAgents === null || directAgents >= requiredDirectAgents) && (requiredAnnualSalesSen === null || annualSalesSen >= requiredAnnualSalesSen);
  return { currentLevel: level, successfulCases: { current: successfulCases, required: requiredCases }, directAgents: { current: directAgents, required: requiredDirectAgents }, annualSalesSen: { current: annualSalesSen, required: requiredAnnualSalesSen }, eligibleForPromotion, nextLevel };
};
export const mockAgents: AgentSummary[] = [
  { id: "agent-001", agentCode: "AG-001", displayName: "Aisha Rahman", currentLevel: 2 as const, uplineAgentId: null, uplineName: null, directAgentCount: 2, successfulCaseCount: 8, personalSalesSen: 11240000, referralSalesSen: 6875000, annualSalesSen: 11240000, commissionEarnedSen: 468320, status: "active" as const, qualification: buildQualification(2, 8, 2, 11240000), promotionHistory: [], levelChangeRequests: [] },
  { id: "agent-002", agentCode: "AG-002", displayName: "Daniel Lim", currentLevel: 1 as const, uplineAgentId: "agent-001", uplineName: "Aisha Rahman", directAgentCount: 0, successfulCaseCount: 3, personalSalesSen: 5725000, referralSalesSen: 0, annualSalesSen: 5725000, commissionEarnedSen: 192840, status: "active" as const, qualification: buildQualification(1, 3, 0, 5725000), promotionHistory: [], levelChangeRequests: [] },
  { id: "agent-003", agentCode: "AG-003", displayName: "Nadia Yusuf", currentLevel: 1 as const, uplineAgentId: "agent-001", uplineName: "Aisha Rahman", directAgentCount: 0, successfulCaseCount: 1, personalSalesSen: 2450000, referralSalesSen: 0, annualSalesSen: 2450000, commissionEarnedSen: 104832, status: "active" as const, qualification: buildQualification(1, 1, 0, 2450000), promotionHistory: [], levelChangeRequests: [] },
  { id: "agent-004", agentCode: "AG-004", displayName: "Hafiz Roslan", currentLevel: 1 as const, uplineAgentId: "agent-001", uplineName: "Aisha Rahman", directAgentCount: 1, successfulCaseCount: 7, personalSalesSen: 9340000, referralSalesSen: 1180000, annualSalesSen: 9340000, commissionEarnedSen: 356400, status: "active" as const, qualification: buildQualification(1, 7, 1, 9340000), promotionHistory: [], levelChangeRequests: [] },
];
export function mockDashboard(role: UserRole): DashboardSnapshot { const currentUser = role === "agent" ? { id: "user-001", role, displayName: "Aisha Rahman", email: "aisha@smartegy.example", agentId: "agent-001" } : role === "staff" ? { id: "user-002", role, displayName: "Farid Iskandar", email: "farid@smartegy.example", agentId: null } : { id: "user-003", role, displayName: "Mei Tan", email: "mei@smartegy.example", agentId: null }; return { currentUser, cases: role === "agent" ? mockCases.filter((item) => item.agentId === "agent-001") : mockCases, commissions: role === "agent" ? mockCommissions.filter((item) => item.recipientId === "agent-001") : mockCommissions, agents: mockAgents }; }
