import type { AgentMonthlyPayout, CurrentUser, PayoutMonthSummary, PayoutSettlementStatus, PayoutTransaction } from "./types";
import { downloadCsv } from "./export-csv";

type PayoutErrorCode = "FORBIDDEN" | "NOT_FOUND" | "CONFLICT";
export type PayoutResult<T> = { ok: true; data: T } | { ok: false; error: { code: PayoutErrorCode; message: string } };
export interface PayoutDirectoryQuery { search?: string; agentId?: string; settlementStatus?: PayoutSettlementStatus | AgentMonthlyPayout["settlementStatus"] | "all"; page?: number; pageSize?: number; sortBy?: "agent" | "date"; sortDirection?: "asc" | "desc"; view?: "agents" | "transactions"; }
export interface PayoutMonthData { summary: PayoutMonthSummary; agentPayouts: AgentMonthlyPayout[]; transactions: PayoutTransaction[]; totalItems?: number; totalPages?: number; }
export interface PayoutRepository { getMonth(actor: CurrentUser, payoutMonth: string, query?: PayoutDirectoryQuery): Promise<PayoutResult<PayoutMonthData>>; exportMonth(actor: CurrentUser, payoutMonth: string): Promise<PayoutResult<true>>; exportTransactions(actor: CurrentUser, payoutMonth: string, query?: PayoutDirectoryQuery): Promise<PayoutResult<true>>; settleTransaction(actor: CurrentUser, input: { transactionId: string; bankReference: string; payoutMonth?: string }): Promise<PayoutResult<PayoutTransaction>>; }

const initialTransactions: PayoutTransaction[] = [
  { id: "payout-001", payoutMonth: "2026-09", agentId: "agent-001", agentName: "Aisha Rahman", agentCode: "AG-001", bankAccount: { bankName: "Maybank", accountHolderName: "Aisha Rahman", accountNumberMasked: "•••• 4581" }, commissionId: "com-001", caseNumber: "SMG-00124", customerDisplayName: "Kencana Packaging Sdn Bhd", amountSen: 1760, settlementStatus: "pending", settledAt: null, settledById: null, settledByDisplayName: null, bankReference: null },
  { id: "payout-002", payoutMonth: "2026-09", agentId: "agent-002", agentName: "Daniel Lim", agentCode: "AG-002", bankAccount: { bankName: "CIMB", accountHolderName: "Daniel Lim", accountNumberMasked: "•••• 9132" }, commissionId: "com-002", caseNumber: "SMG-00124", customerDisplayName: "Kencana Packaging Sdn Bhd", amountSen: 2782, settlementStatus: "pending", settledAt: null, settledById: null, settledByDisplayName: null, bankReference: null },
  { id: "payout-003", payoutMonth: "2026-09", agentId: "agent-001", agentName: "Aisha Rahman", agentCode: "AG-001", bankAccount: { bankName: "Maybank", accountHolderName: "Aisha Rahman", accountNumberMasked: "•••• 4581" }, commissionId: "com-003", caseNumber: "SMG-00131", customerDisplayName: "Seri Maju Trading", amountSen: 2450, settlementStatus: "pending", settledAt: null, settledById: null, settledByDisplayName: null, bankReference: null },
  { id: "payout-004", payoutMonth: "2026-09", agentId: "agent-004", agentName: "Hafiz Roslan", agentCode: "AG-004", bankAccount: { bankName: "Public Bank", accountHolderName: "Hafiz Roslan", accountNumberMasked: "•••• 6804" }, commissionId: "com-004", caseNumber: "SMG-00132", customerDisplayName: "Murni Engineering", amountSen: 3125, settlementStatus: "settled", settledAt: "2026-09-16T09:20:00Z", settledById: "user-002", settledByDisplayName: "Farid Iskandar", bankReference: "PBK-SEP-00034" },
];
let transactions: PayoutTransaction[] = structuredClone(initialTransactions);
function allowed(actor: CurrentUser) { return actor.role === "staff" || actor.role === "admin"; }
function fail<T>(code: PayoutErrorCode, message: string): PayoutResult<T> { return { ok: false, error: { code, message } }; }
function aggregate(payoutMonth: string, items: PayoutTransaction[]) {
  const groups = new Map<string, PayoutTransaction[]>(); items.forEach((item) => groups.set(item.agentId, [...(groups.get(item.agentId) ?? []), item]));
  const agentPayouts: AgentMonthlyPayout[] = Array.from(groups.values()).map((entries) => { const first = entries[0]; const totalSen = entries.reduce((sum, item) => sum + item.amountSen, 0); const settledSen = entries.filter((item) => item.settlementStatus === "settled").reduce((sum, item) => sum + item.amountSen, 0); const settledTransactionCount = entries.filter((item) => item.settlementStatus === "settled").length; const settlementStatus: AgentMonthlyPayout["settlementStatus"] = settledTransactionCount === entries.length ? "settled" : settledTransactionCount ? "partially_settled" : "pending"; return { agentId: first.agentId, agentName: first.agentName, agentCode: first.agentCode, bankAccount: first.bankAccount, payoutMonth, totalSen, settledSen, pendingSen: totalSen - settledSen, transactionCount: entries.length, settledTransactionCount, settlementStatus }; }).toSorted((a, b) => a.agentName.localeCompare(b.agentName));
  const totalSen = items.reduce((sum, item) => sum + item.amountSen, 0); const settledSen = items.filter((item) => item.settlementStatus === "settled").reduce((sum, item) => sum + item.amountSen, 0); const settledTransactionCount = items.filter((item) => item.settlementStatus === "settled").length;
  return { summary: { payoutMonth, totalSen, settledSen, pendingSen: totalSen - settledSen, agentCount: agentPayouts.length, settledAgentCount: agentPayouts.filter((item) => item.settlementStatus === "settled").length, transactionCount: items.length, settledTransactionCount }, agentPayouts };
}
export const mockPayoutRepository: PayoutRepository = {
  async getMonth(actor, payoutMonth) { if (!allowed(actor)) return fail("FORBIDDEN", "Only staff and administrators can view payout data."); const items = transactions.filter((item) => item.payoutMonth === payoutMonth); return { ok: true, data: { ...aggregate(payoutMonth, items), transactions: structuredClone(items) } }; },
  async exportMonth(actor, payoutMonth) { if (!allowed(actor)) return fail("FORBIDDEN", "Only staff and administrators can export payout data."); const items = transactions.filter((item) => item.payoutMonth === payoutMonth); const rows = [["Agent", "Agent ID", "Agent Code", "Bank", "Account Holder", "Account Number", "Payout Month", "Total Payout", "Pending Amount", "Settled Amount", "Transaction Count", "Settlement Status"], ...aggregate(payoutMonth, items).agentPayouts.map((item) => [item.agentName, item.agentId, item.agentCode, item.bankAccount.bankName, item.bankAccount.accountHolderName, item.bankAccount.accountNumberMasked, item.payoutMonth, (item.totalSen / 100).toFixed(2), (item.pendingSen / 100).toFixed(2), (item.settledSen / 100).toFixed(2), item.transactionCount, item.settlementStatus])]; downloadCsv(`smartegy-payouts-${payoutMonth}.csv`, rows); return { ok: true, data: true }; },
  async exportTransactions(actor, payoutMonth, query = {}) { if (!allowed(actor)) return fail("FORBIDDEN", "Only staff and administrators can export payout data."); const search = query.search?.trim().toLowerCase() ?? ""; const items = transactions.filter((item) => item.payoutMonth === payoutMonth && (!query.agentId || item.agentId === query.agentId) && (!query.settlementStatus || query.settlementStatus === "all" || (query.settlementStatus === "settled" ? item.settlementStatus === "settled" : item.settlementStatus !== "settled")) && (!search || [item.agentName, item.agentCode, item.caseNumber, item.customerDisplayName, item.bankAccount.bankName].some((value) => value.toLowerCase().includes(search)))); const rows = [["Agent", "Agent ID", "Agent Code", "Bank", "Account Holder", "Account Number", "Payout Month", "Case", "Customer", "Amount", "Settlement", "Paid At", "Bank Reference"], ...items.map((item) => [item.agentName, item.agentId, item.agentCode, item.bankAccount.bankName, item.bankAccount.accountHolderName, item.bankAccount.accountNumberMasked, item.payoutMonth, item.caseNumber, item.customerDisplayName, (item.amountSen / 100).toFixed(2), item.settlementStatus, item.settledAt ?? "", item.bankReference ?? ""])]; downloadCsv(`smartegy-payout-transactions-${payoutMonth}.csv`, rows); return { ok: true, data: true }; },
  async settleTransaction(actor, input) { if (!allowed(actor)) return fail("FORBIDDEN", "Only staff and administrators can settle a payout transaction."); const transaction = transactions.find((item) => item.id === input.transactionId); if (!transaction) return fail("NOT_FOUND", "Payout transaction not found."); if (transaction.settlementStatus === "settled") return fail("CONFLICT", "This payout transaction is already settled."); if (!input.bankReference.trim()) return fail("CONFLICT", "Enter the bank settlement reference."); transaction.settlementStatus = "settled"; transaction.settledAt = new Date().toISOString(); transaction.settledById = actor.id; transaction.settledByDisplayName = actor.displayName; transaction.bankReference = input.bankReference.trim(); return { ok: true, data: structuredClone(transaction) }; },
};
export function resetMockPayouts() { transactions = structuredClone(initialTransactions); }

import { isSupabaseConfigured } from "./supabase-browser";
import { supabasePayoutRepository } from "./supabase-payout-repository";
export const payoutRepository: PayoutRepository = isSupabaseConfigured() ? supabasePayoutRepository : mockPayoutRepository;
