"use client";
import { TextInput, TextArea } from "@/components/form-controls";

import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { AppShell } from "@/components/app-shell";
import { Badge, Button, EmptyState, ErrorState, LoadingState, PermissionDenied, StatCard } from "@/components/ui";
import { DataTable } from "@/components/data-table";
import { FilterSelect } from "@/components/filter-select";
import { TableFooter } from "@/components/table-footer";
import { downloadCsv } from "@/lib/export-csv";
import { formatDate, formatMoney } from "@/lib/format";
import { agentRepository } from "@/lib/agent-repository";
import { usePreviewUser } from "@/lib/preview-user";
import type { AgentLevelChangeApproval } from "@/lib/types";

const pageSize = 5;
const statuses: Array<AgentLevelChangeApproval["status"] | "all"> = ["all", "pending", "approved", "rejected"];

export default function ApprovalsPage() {
  const { user, setRole } = usePreviewUser("admin");
  const [items, setItems] = useState<AgentLevelChangeApproval[]>([]);
  const [state, setState] = useState<"loading" | "error" | "permission" | "ready">("loading");
  const [selected, setSelected] = useState<AgentLevelChangeApproval | null>(null);
  const [decision, setDecision] = useState<"approve" | "reject" | null>(null);
  const [note, setNote] = useState("");
  const [feedback, setFeedback] = useState<string | null>(null);
  const load = useCallback(async () => { setState("loading"); const result = await agentRepository.listLevelChangeApprovals(user); if (result.ok) { setItems(result.data); setState("ready"); } else setState(result.error.code === "FORBIDDEN" ? "permission" : "error"); }, [user]);
  useEffect(() => { void load(); }, [load]);
  async function review() { if (!selected || !decision) return; const result = await agentRepository.reviewLevelChange(user, { agentId: selected.agentId, requestId: selected.id, decision, note }); if (result.ok) { setFeedback(`${selected.agent.displayName}'s level-change request was ${decision === "approve" ? "approved and applied" : "rejected"}.`); setSelected(null); setDecision(null); setNote(""); void load(); } else setFeedback(result.error.message); }
  return <AppShell user={user} onRoleChange={setRole}><main className="page-content approvals-page"><div className="page-header"><div><p className="eyebrow">Administrator workspace</p><h1>Approvals</h1><p className="page-description">Review and decide agent level-change requests.</p></div></div>{state === "loading" ? <LoadingState/> : state === "permission" ? <PermissionDenied/> : state === "error" ? <ErrorState onRetry={load}/> : <ApprovalContent items={items} onReview={setSelected}/>} {feedback && <div className="action-feedback" role="status">{feedback}<button type="button" onClick={() => setFeedback(null)} aria-label="Dismiss message">×</button></div>} {selected && <ReviewDialog item={selected} decision={decision} note={note} setDecision={setDecision} setNote={setNote} onCancel={() => { setSelected(null); setDecision(null); setNote(""); }} onConfirm={review}/>}</main></AppShell>;
}

function ApprovalContent({ items, onReview }: { items: AgentLevelChangeApproval[]; onReview: (item: AgentLevelChangeApproval) => void }) {
  const [search, setSearch] = useState(""); const [status, setStatus] = useState<AgentLevelChangeApproval["status"] | "all">("pending"); const [type, setType] = useState<"all" | "promotion" | "demotion">("all"); const [page, setPage] = useState(1);
  const filtered = useMemo(() => { const query = search.trim().toLowerCase(); return items.filter((item) => (!query || [item.id, item.agent.displayName, item.agent.agentCode, item.requestedByDisplayName].some((value) => value.toLowerCase().includes(query))) && (status === "all" || item.status === status) && (type === "all" || (type === "promotion" ? item.requestedLevel > item.previousLevel : item.requestedLevel < item.previousLevel))); }, [items, search, status, type]);
  const totalPages = Math.max(1, Math.ceil(filtered.length / pageSize)); const currentPage = Math.min(page, totalPages); const visible = filtered.slice((currentPage - 1) * pageSize, currentPage * pageSize); const pending = items.filter((item) => item.status === "pending");
  const reset = () => { setSearch(""); setStatus("pending"); setType("all"); setPage(1); };
  return <><div className="stat-grid approvals-summary"><StatCard label="Pending approvals" value={String(pending.length)} detail="Awaiting an administrator" accent/><StatCard label="Promotions" value={String(pending.filter((item) => item.requestedLevel > item.previousLevel).length)} detail="Pending requests"/><StatCard label="Demotions" value={String(pending.filter((item) => item.requestedLevel < item.previousLevel).length)} detail="Pending requests"/><StatCard label="Reviewed" value={String(items.filter((item) => item.status !== "pending").length)} detail="Approval history"/></div><section className="panel case-table-panel"><div className="panel-header case-table-header"><div><h2>Level-change requests</h2><p>Pending requests are prioritised for review.</p></div><span className="case-count">{filtered.length} requests</span></div><div className="case-filters" aria-label="Approval filters"><label><span>Search</span><TextInput type="search" value={search} onChange={(event) => { setSearch(event.target.value); setPage(1); }} placeholder="Request, agent, or staff"/></label><label><span>Request type</span><FilterSelect allLabel="All request types" value={type} options={["all", "promotion", "demotion"]} onChange={(value) => { setType(value); setPage(1); }}/></label><label><span>Status</span><FilterSelect allLabel="All statuses" value={status} options={statuses} onChange={(value) => { setStatus(value); setPage(1); }}/></label><button className="text-button case-filter-reset" type="button" onClick={reset} disabled={!search && status === "pending" && type === "all"}>Clear filters</button></div>{visible.length ? <DataTable caption="Level change approvals" headers={["Request", "Agent", "Level change", "Qualification", "Requested by", "Requested", "Status", "Review"]}>{visible.map((item) => <ApprovalRow key={item.id} item={item} onReview={onReview}/>)}</DataTable> : <EmptyState title={items.length ? "No matching approvals" : "No level-change requests"} description={items.length ? "Try changing or clearing the filters." : "Staff level-change requests will appear here for administrator review."}/>}<TableFooter currentPage={currentPage} totalPages={totalPages} visibleCount={visible.length} totalCount={filtered.length} onPageChange={setPage} onExport={() => downloadCsv("smartegy-level-change-approvals.csv", [["Request", "Agent", "Agent ID", "Current level", "Requested level", "Requested by", "Requested", "Status", "Reason"], ...filtered.map((item) => [item.id, item.agent.displayName, item.agent.agentCode, item.previousLevel, item.requestedLevel, item.requestedByDisplayName, item.requestedAt, item.status, item.reason ?? ""])])} exportLabel="Export"/></section></>;
}

function ApprovalRow({ item, onReview }: { item: AgentLevelChangeApproval; onReview: (item: AgentLevelChangeApproval) => void }) { const promotion = item.requestedLevel > item.previousLevel; const qualification = item.agent.qualification; return <tr className="case-table-row" tabIndex={0} onClick={() => onReview(item)} onKeyDown={(event) => { if (event.key === "Enter") onReview(item); }}><td><span className="table-primary">{item.id}</span><span className="table-secondary">{promotion ? "Promotion" : "Demotion"}</span></td><td><Link className="table-primary" href={`/agents/${item.agentId}`} onClick={(event) => event.stopPropagation()}>{item.agent.displayName}</Link><span className="table-secondary">{item.agent.agentCode}</span></td><td>Level {item.previousLevel} → Level {item.requestedLevel}</td><td>{promotion ? <span className="table-secondary">{qualification.successfulCases.current}/{qualification.successfulCases.required ?? "–"} cases · {qualification.directAgents.current}/{qualification.directAgents.required ?? "–"} recruits · {formatMoney(qualification.annualSalesSen.current)}</span> : <span className="muted-cell">Not required for demotion</span>}</td><td>{item.requestedByDisplayName}</td><td>{formatDate(item.requestedAt)}</td><td><Badge status={item.status}/></td><td>{item.status === "pending" ? <Button size="sm" className="agent-promote-button" onClick={(event) => { event.stopPropagation(); onReview(item); }}>Review</Button> : <Button size="sm" variant="secondary" onClick={(event) => { event.stopPropagation(); onReview(item); }}>View</Button>}</td></tr>; }

function ReviewDialog({ item, decision, note, setDecision, setNote, onCancel, onConfirm }: { item: AgentLevelChangeApproval; decision: "approve" | "reject" | null; note: string; setDecision: (value: "approve" | "reject" | null) => void; setNote: (value: string) => void; onCancel: () => void; onConfirm: () => void }) { const promotion = item.requestedLevel > item.previousLevel; const qualification = item.agent.qualification; return <div className="dialog-backdrop" role="presentation"><div className="dialog approval-dialog" role="dialog" aria-modal="true" aria-labelledby="approval-dialog-title"><h2 id="approval-dialog-title">Review level-change request</h2><p>{item.agent.displayName} ({item.agent.agentCode}) · Level {item.previousLevel} → Level {item.requestedLevel}</p><dl className="approval-detail-list"><div><dt>Requested by</dt><dd>{item.requestedByDisplayName} · {formatDate(item.requestedAt)}</dd></div><div><dt>Request reason</dt><dd>{item.reason ?? "No reason recorded"}</dd></div>{promotion && <div><dt>Qualification evidence</dt><dd>{qualification.successfulCases.current}/{qualification.successfulCases.required ?? "–"} successful cases · {qualification.directAgents.current}/{qualification.directAgents.required ?? "–"} recruits · {formatMoney(qualification.annualSalesSen.current)} annual sales</dd></div>}<div><dt>Previous approval history</dt><dd>{item.agent.promotionHistory.length ? item.agent.promotionHistory.map((audit) => `Level ${audit.previousLevel} → ${audit.newLevel} · ${formatDate(audit.occurredAt)}`).join("; ") : "No previous level changes"}</dd></div></dl>{item.status === "pending" ? <><label className="settlement-field" htmlFor="approval-note">{decision === "reject" ? "Rejection reason" : "Review note (optional)"}<TextArea id="approval-note" rows={3} value={note} onChange={(event) => setNote(event.target.value)} placeholder={decision === "reject" ? "Required to reject this request" : "Internal approval note"}/></label><div className="dialog-actions approval-dialog-actions"><Button variant="secondary" onClick={onCancel}>Cancel</Button><Button variant="danger" onClick={() => setDecision("reject")}>Reject</Button><Button className="agent-promote-button" onClick={() => setDecision("approve")}>Approve</Button></div>{decision && <div className="approval-confirm"><p>Confirm {decision === "approve" ? "approval and apply" : "rejection"} for {item.agent.displayName}?</p><Button variant="secondary" size="sm" onClick={() => setDecision(null)}>Back</Button><Button className={decision === "approve" ? "agent-promote-button" : ""} variant={decision === "reject" ? "danger" : "primary"} size="sm" disabled={decision === "reject" && !note.trim()} onClick={onConfirm}>Confirm {decision}</Button></div>}</> : <div className="dialog-actions"><Button variant="secondary" onClick={onCancel}>Close</Button></div>}</div></div>; }
