"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { AppShell } from "@/components/app-shell";
import { Badge, Button, EmptyState, ErrorState, LoadingState, PermissionDenied, StatCard } from "@/components/ui";
import { DataTable } from "@/components/data-table";
import { Icon } from "@/components/icons";
import { formatDate, formatMoney } from "@/lib/format";
import { mockRepository } from "@/lib/mock-repository";
import { roleLabels } from "@/lib/navigation";
import type { DashboardSnapshot, UserRole } from "@/lib/types";

export default function DashboardPage() { const [role, setRole] = useState<UserRole>("agent"); const [snapshot, setSnapshot] = useState<DashboardSnapshot | null>(null); const [loading, setLoading] = useState(true); const [failed, setFailed] = useState(false); useEffect(() => { setLoading(true); setFailed(false); mockRepository.getSnapshot(role).then(setSnapshot).catch(() => setFailed(true)).finally(() => setLoading(false)); }, [role]); const user = snapshot?.currentUser ?? { id: "preview", role, displayName: roleLabels[role], email: null, agentId: null }; return <AppShell user={user} onRoleChange={setRole}><div className="page-content"><div className="page-header"><div><p className="eyebrow">{roleLabels[role]} workspace</p><h1>{role === "agent" ? "Good morning, Aisha" : "Operations overview"}</h1><p className="page-description">Here’s what needs your attention today.</p></div><div className="page-actions">{role === "agent" && <Link className="button button-primary" href="/cases/new"><Icon name="plus" size={17}/> Submit new case</Link>}<button className="button button-secondary"><Icon name="arrow" size={17}/> Export view</button></div></div><div className="preview-banner"><span className="preview-dot"/><div><strong>Development preview</strong><span> Role switching uses mock data only. Production authorization will be enforced server-side.</span></div></div>{loading ? <LoadingState/> : failed ? <ErrorState onRetry={() => setRole(role)}/> : snapshot && <DashboardContent snapshot={snapshot} role={role}/>}</div></AppShell>; }

function DashboardContent({ snapshot, role }: { snapshot: DashboardSnapshot; role: UserRole }) { const isAgent = role === "agent"; const isFinance = role === "finance_management"; const activeCases = snapshot.cases.filter((item) => !["completed"].includes(item.status)); const sales = snapshot.cases.reduce((sum, item) => sum + (item.saleAmountSen ?? 0), 0); const commissions = snapshot.commissions.reduce((sum, item) => sum + item.entitlementSen, 0); return <>{isAgent ? <><section className="focus-panel"><div><p className="eyebrow">Current qualification</p><h2>Level 2 <span className="muted">· progressing well</span></h2><p className="focus-copy">You’re 4 successful cases away from the next level. Keep your momentum going.</p><div className="progress"><span style={{ width: "64%" }}/></div><div className="progress-meta"><span>8 of 12 successful cases</span><span>67%</span></div></div><div className="focus-side"><span className="level-circle">L2</span><span>Personal progress</span><Link href="/settings/profile">View details <Icon name="arrow" size={14}/></Link></div></section><div className="stat-grid"><StatCard label="Active cases" value={String(activeCases.length)} detail="Across 2 statuses" accent/><StatCard label="Successful cases" value="8" detail="+2 this quarter"/><StatCard label="Personal sales" value={formatMoney(11240000)} detail="Year to date"/><StatCard label="Commissions earned" value={formatMoney(commissions)} detail="1 payment scheduled"/></div></> : <><section className="focus-panel admin-focus"><div><p className="eyebrow">Operational priority</p><h2>{isFinance ? "Commission review queue" : "Cases needing attention"}</h2><p className="focus-copy">{isFinance ? "2 commission entries are ready for financial review." : "2 cases and 1 payment are waiting for an update."}</p><div className="priority-list"><span><i className="priority-dot warning"/>Pending review <strong>2</strong></span><span><i className="priority-dot danger"/>Payment verification <strong>1</strong></span></div></div><div className="focus-side"><span className="priority-number">{isFinance ? "RM1,347.50" : "03"}</span><span>{isFinance ? "Ready to review" : "Open priorities"}</span><Link href={isFinance ? "/commissions" : "/cases"}>Open queue <Icon name="arrow" size={14}/></Link></div></section><div className="stat-grid"><StatCard label="Total cases" value="128" detail="+12 this month" accent/><StatCard label="Sales this month" value={formatMoney(sales)} detail="Across 4 cases"/><StatCard label="Commission payable" value={formatMoney(468320)} detail="18 entries"/><StatCard label="Paid commissions" value={formatMoney(892140)} detail="This quarter"/></div></>}
<div className="dashboard-grid"><section className="panel recent-panel"><div className="panel-header"><div><h2>{isAgent ? "Recent case activity" : "Recent cases"}</h2><p>{isAgent ? "Your latest submissions and updates" : "Latest activity across your workspace"}</p></div><Link className="text-link" href="/cases">View all <Icon name="arrow" size={14}/></Link></div>{snapshot.cases.length ? <DataTable caption="Recent cases" headers={["Case", "Customer", "Status", "Updated"]}>{snapshot.cases.slice(0, 4).map((item) => <tr key={item.id}><td><Link className="table-primary" href={`/cases/${item.id}`}>{item.caseNumber}</Link><span className="table-secondary">{formatMoney(item.saleAmountSen)}</span></td><td>{item.customerDisplayName}<span className="table-secondary">{item.agentName}</span></td><td><Badge status={item.status}/></td><td className="muted-cell">{formatDate(item.updatedAt)}</td></tr>)}</DataTable> : <EmptyState title="No cases yet" description="New cases will appear here."/>}</section><section className="panel side-panel"><div className="panel-header"><div><h2>{isAgent ? "Upcoming commissions" : "Team snapshot"}</h2><p>{isAgent ? "Scheduled payments" : "Agent performance"}</p></div><Link className="text-link" href={isAgent ? "/commissions" : "/agents"}>View all <Icon name="arrow" size={14}/></Link></div>{isAgent ? snapshot.commissions.length ? <div className="commission-list">{snapshot.commissions.map((item) => <div className="commission-item" key={item.id}><div><strong>{item.commissionNumber}</strong><span>{formatDate(item.nextPaymentDate ?? "2026-08-15")}</span></div><div className="commission-amount">{formatMoney(item.nextPaymentSen)}<Badge status={item.status}/></div></div>)}</div> : <EmptyState title="No scheduled payments"/> : <div className="team-list">{snapshot.agents.map((agent) => <div className="team-item" key={agent.id}><span className="avatar avatar-small">{agent.displayName.split(" ").map((name) => name[0]).join("")}</span><div><strong>{agent.displayName}</strong><span>Level {agent.currentLevel} · {agent.successfulCaseCount} successful cases</span></div><span className="team-sales">{formatMoney(agent.personalSalesSen)}</span></div>)}</div>}</section></div></>; }
